apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "lgtm-auth-proxy.fullname" $ }}-config
  labels:
    {{- include "lgtm-auth-proxy.labels" $ | nindent 4 }}
data:
  config.toml: |
{{ tpl $.Values.config $ | indent 4 }}
