name: "PR Checks"

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened

permissions: read-all

jobs:
  helm-lint:
    name: Helm lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.11.1
      - name: Lint Chart
        run: helm lint charts/*
  pr-semver:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
